# Generated by Django 5.2.17 on 2026-09-07 13:07

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImdbWatchlistConnection",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("source_url", models.URLField(max_length=512)),
                ("profile_id", models.CharField(max_length=160)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("next_refresh_at", models.DateTimeField()),
                ("title_count", models.PositiveIntegerField(default=0)),
                ("last_added", models.PositiveIntegerField(default=0)),
                ("last_error", models.CharField(blank=True, max_length=32, null=True)),
                ("lease_id", models.UUIDField(blank=True, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("snapshot_ids", models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name="RoomMember",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="room_membership",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("display_name", models.CharField(max_length=80)),
                (
                    "role",
                    models.CharField(
                        choices=[("owner", "Owner"), ("member", "Member")],
                        default="member",
                        max_length=10,
                    ),
                ),
                (
                    "slot",
                    models.PositiveSmallIntegerField(choices=[(1, "One"), (2, "Two")], unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("slot",),
            },
        ),
        migrations.CreateModel(
            name="SpotifyAccount",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("spotify_id", models.CharField(max_length=160)),
                ("display_name", models.CharField(blank=True, max_length=160)),
                ("token_box", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RoomEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=240)),
                ("kind", models.CharField(max_length=32)),
                ("action", models.CharField(max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="room_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="SpotifyState",
            fields=[
                (
                    "state_hash",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("verifier_box", models.TextField()),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoomEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("book", "Book"),
                            ("music", "Music"),
                            ("wish", "Wish"),
                            ("request", "Request"),
                            ("note", "Note"),
                            ("film", "Film"),
                            ("game", "Game"),
                            ("rabbit_hole", "Rabbit hole"),
                            ("movie_night", "Movie night"),
                            ("adventure", "Adventure"),
                            ("lyric", "Lyric"),
                        ],
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=240)),
                ("creator", models.CharField(blank=True, max_length=180)),
                ("note", models.TextField(blank=True)),
                ("status", models.CharField(max_length=32)),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                ("rating", models.PositiveSmallIntegerField(default=0)),
                ("format", models.CharField(blank=True, max_length=80)),
                ("link", models.URLField(blank=True, max_length=2000)),
                ("image_url", models.URLField(blank=True, max_length=2000, null=True)),
                (
                    "image_file",
                    models.FileField(blank=True, null=True, upload_to="room/images/%Y/%m/"),
                ),
                (
                    "recording_file",
                    models.FileField(blank=True, null=True, upload_to="room/recordings/%Y/%m/"),
                ),
                (
                    "recording_type",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("source_id", models.CharField(blank=True, max_length=200, null=True)),
                ("provider_added_at", models.DateTimeField(blank=True, null=True)),
                (
                    "provider_album",
                    models.CharField(blank=True, max_length=240, null=True),
                ),
                (
                    "provider_release_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("details", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="room_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("source_id__isnull", False)),
                        fields=("kind", "source_id"),
                        name="room_entry_source_unique",
                    )
                ],
            },
        ),
    ]
