# Generated by Django 5.2.17 on 2026-09-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomentry",
            name="shelf_cubby",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="roomentry",
            name="shelf_orientation",
            field=models.CharField(
                choices=[("vertical", "Vertical"), ("horizontal", "Horizontal")],
                default="vertical",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="roomentry",
            name="shelf_position",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="roomentry",
            name="shelf_stack",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
