# Generated by Django 5.2.17 on 2026-09-09 09:21

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0002_roomentry_shelf_cubby_roomentry_shelf_orientation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShelfLayout",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ShelfDecoration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("bust", "Bust"),
                            ("vase", "Vase"),
                            ("globe", "Globe"),
                            ("plant", "Plant"),
                            ("candle", "Candle"),
                            ("postcard", "Postcard"),
                            ("ticket", "Ticket"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(max_length=80)),
                ("cubby", models.PositiveSmallIntegerField(default=0)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "image_file",
                    models.FileField(blank=True, null=True, upload_to="room/decor/%Y/%m/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
